# Generated by Django 5.0.1 on 2024-01-15 07:02
#https://docs.djangoproject.com/en/5.0/ref/migration-operations/
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('deptno', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(blank=True, max_length=20, null=True)),
                ('loc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empno', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('mgr', models.IntegerField(blank=True, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('my_name', models.CharField(max_length=70, null=True)),
                ('my_addr', models.CharField(blank=True, max_length=70, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'm_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='address03',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('my_name', models.CharField(max_length=70, null=True)),
                ('my_addr', models.CharField(blank=True, max_length=70, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'm_address03',
                'managed': True,
            },
        ),
    ]
