# Generated by Django 5.0.1 on 2024-01-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm01', '0002_address02'),
    ]

    operations = [
        migrations.CreateModel(
            name='address02',
            fields=[
                ('my_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('my_addr', models.CharField(blank=True, max_length=70, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'm_address02',
                'managed': True,
            },
        ),
    ]
