# Generated by Django 5.0.1 on 2024-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "select_option",
                    models.CharField(
                        choices=[
                            ("전기/기사", "전기/기사"),
                            ("통신/IT", "통신/IT"),
                            ("은행/증권/보험", "은행/증권/보험"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
